# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: x:/fpga_pll_mash111_dtc_ssc/FPGA_SSC_PLL/FPGA_SSC_PLL.srcs/sources_1/ip/ila_cal_top/ila_cal_top.xci
# IP: The module: 'ila_cal_top' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: x:/fpga_pll_mash111_dtc_ssc/FPGA_SSC_PLL/FPGA_SSC_PLL.gen/sources_1/ip/ila_cal_top/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_cal_top'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: x:/fpga_pll_mash111_dtc_ssc/FPGA_SSC_PLL/FPGA_SSC_PLL.gen/sources_1/ip/ila_cal_top/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_cal_top'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: x:/fpga_pll_mash111_dtc_ssc/FPGA_SSC_PLL/FPGA_SSC_PLL.gen/sources_1/ip/ila_cal_top/ila_cal_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_cal_top'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: x:/fpga_pll_mash111_dtc_ssc/FPGA_SSC_PLL/FPGA_SSC_PLL.srcs/sources_1/ip/ila_cal_top/ila_cal_top.xci
# IP: The module: 'ila_cal_top' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: x:/fpga_pll_mash111_dtc_ssc/FPGA_SSC_PLL/FPGA_SSC_PLL.gen/sources_1/ip/ila_cal_top/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_cal_top'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: x:/fpga_pll_mash111_dtc_ssc/FPGA_SSC_PLL/FPGA_SSC_PLL.gen/sources_1/ip/ila_cal_top/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_cal_top'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: x:/fpga_pll_mash111_dtc_ssc/FPGA_SSC_PLL/FPGA_SSC_PLL.gen/sources_1/ip/ila_cal_top/ila_cal_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_cal_top'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
