import os
os.chdir(r"D:\GS\项目\FPGA\xcvu9p-flga2104-2L-e\fpga_pll_mash111_dtc_ssc\RTL\testbench\openclaw")

# ========== xilinx_sim.v ==========
sim_lines = []
sim_lines.append("`timescale 1ns / 1ps")
sim_lines.append("module IBUFDS #(parameter DIFF_TERM=\"FALSE\", parameter IBUF_LOW_PWR=\"TRUE\", parameter IOSTANDARD=\"DEFAULT\") (output O, input I, input IB);")
sim_lines.append("    assign O = I;")
sim_lines.append("endmodule")
sim_lines.append("module OBUFDS #(parameter IOSTANDARD=\"DEFAULT\", parameter SLEW=\"SLOW\") (output O, output OB, input I);")
sim_lines.append("    assign O = I; assign OB = ~I;")
sim_lines.append("endmodule")
sim_lines.append("module BUFG (output O, input I);")
sim_lines.append("    assign O = I;")
sim_lines.append("endmodule")
sim_lines.append("module BUFGMUX #(parameter CLK_SEL_TYPE=\"SYNC\") (output O, input I0, input I1, input S);")
sim_lines.append("    assign O = S ? I1 : I0;")
sim_lines.append("endmodule")
sim_lines.append("// VIO stubs")
sim_lines.append("module vio_0 (input clk, input [0:0] probe_in0, input [0:0] probe_in1, output [7:0] probe_out0, output [9:0] probe_out1, output [9:0] probe_out2, output [2:0] probe_out3, output [9:0] probe_out4, output [8:0] probe_out5, output [0:0] probe_out6);")
sim_lines.append("    assign probe_out0 = 8'd71; assign probe_out1 = 10'd213; assign probe_out2 = 10'd200;")
sim_lines.append("    assign probe_out3 = 3'd1; assign probe_out4 = 10'd12; assign probe_out5 = 9'd0; assign probe_out6 = 1'd0;")
sim_lines.append("endmodule")
sim_lines.append("module vio_cal (input clk, output probe_out0, output probe_out1, output probe_out2, input [9:0] probe_in0, input [0:0] probe_in1);")
sim_lines.append("    reg [7:0] cnt = 0; reg cal_start_r = 0;")
sim_lines.append("    assign probe_out0 = cal_start_r; assign probe_out1 = 1'b0; assign probe_out2 = 1'b0;")
sim_lines.append("    always @(posedge clk) begin")
sim_lines.append("        if (cnt < 8'd100) cnt <= cnt + 1;")
sim_lines.append("        else if (cnt == 8'd100) begin cal_start_r <= 1'b1; cnt <= cnt + 1; end")
sim_lines.append("        else if (cnt == 8'd101) begin cal_start_r <= 1'b0; cnt <= cnt + 1; end")
sim_lines.append("    end")
sim_lines.append("endmodule")
sim_lines.append("module vio_rst (input clk, output [0:0] probe_out0, output [0:0] probe_out1, output [0:0] probe_out2, output [0:0] probe_out3);")
sim_lines.append("    assign probe_out0 = 1'b1; assign probe_out1 = 1'b1; assign probe_out2 = 1'b1; assign probe_out3 = 1'b0;")
sim_lines.append("endmodule")
sim_lines.append("module vio_1 (input clk, output [0:0] probe_out0, output [9:0] probe_out1);")
sim_lines.append("    // Manual dtc_code override for simulation (avoids X from uninit MASH)")
sim_lines.append("    assign probe_out0 = 1'b1; assign probe_out1 = 10'd256;")
sim_lines.append("endmodule")
sim_lines.append("module vio_eo (input clk, output [1:0] probe_out0);")
sim_lines.append("    assign probe_out0 = 2'd0;")
sim_lines.append("endmodule")
sim_lines.append("module test_clk (input clk, output [2:0] probe_out0, output [2:0] probe_out1);")
sim_lines.append("    assign probe_out0 = 3'd0; assign probe_out1 = 3'd0;")
sim_lines.append("endmodule")
sim_lines.append("module ila_0 (input clk, input [0:0] probe0, input [0:0] probe1, input [9:0] probe2, input [2:0] probe3, input [8:0] probe4, input [8:0] probe5, input [0:0] probe6);")
sim_lines.append("endmodule")
sim_lines.append("module ila_1 (input clk, input [9:0] probe0, input [9:0] probe1, input [9:0] probe2, input [9:0] probe3, input [3:0] probe4);")
sim_lines.append("endmodule")
sim_lines.append("module ila_dualdiv (input clk, input [5:0] probe0, input [1:0] probe1, input [1:0] probe2, input [1:0] probe3, input [3:0] probe4, input [0:0] probe5);")
sim_lines.append("endmodule")
sim_lines.append("module mash_stage (input clk, output [1:0] probe_out0, output [1:0] probe_out1);")
sim_lines.append("    assign probe_out0 = 2'd0; assign probe_out1 = 2'd0;")
sim_lines.append("endmodule")
sim_lines.append("module clk_wiz_0 (input clkfb_in, output clk_out1, output clkfb_out, input reset, output locked, input clk_in1);")
sim_lines.append("    reg clk_out_r = 0; reg locked_r = 0; reg [15:0] lock_cnt = 0;")
sim_lines.append("    always begin #1.2 clk_out_r = 1; #0.4 clk_out_r = 0; end")
sim_lines.append("    always @(posedge clk_in1 or posedge reset) begin")
sim_lines.append("        if (reset) begin lock_cnt <= 0; locked_r <= 0; end")
sim_lines.append("        else if (!locked_r) begin if (lock_cnt < 16'd80) lock_cnt <= lock_cnt + 1; else locked_r <= 1; end")
sim_lines.append("    end")
sim_lines.append("    assign clk_out1 = clk_out_r; assign clkfb_out = clk_out_r; assign locked = locked_r;")
sim_lines.append("endmodule")

with open("xilinx_sim.v", "w", newline="\n") as f:
    for line in sim_lines:
        f.write(line + "\n")
print("Written xilinx_sim.v")

# ========== tb_top.v ==========
tb_lines = []
tb_lines.append("`timescale 1ns / 1ps")
tb_lines.append("module tb_top;")
tb_lines.append("    parameter SYS_CLK_PERIOD = 8.0;")
tb_lines.append("    reg sys_clk_p = 0;")
tb_lines.append("    reg sys_clk_n = 0;")
tb_lines.append("    reg sys_rst;")
tb_lines.append("    wire sma_ref_p, sma_ref_n, sma_dtc_p, sma_dtc_n;")
tb_lines.append("")
tb_lines.append("    fpga_ssc_pll_top u_dut (")
tb_lines.append("        .sys_clk_p(sys_clk_p), .sys_clk_n(sys_clk_n), .sys_rst(sys_rst),")
tb_lines.append("        .sma_ref_p(sma_ref_p), .sma_ref_n(sma_ref_n),")
tb_lines.append("        .sma_dtc_p(sma_dtc_p), .sma_dtc_n(sma_dtc_n)")
tb_lines.append("    );")
tb_lines.append("")
tb_lines.append("    always #(SYS_CLK_PERIOD/2) sys_clk_p = ~sys_clk_p;")
tb_lines.append("    always #(SYS_CLK_PERIOD/2) sys_clk_n = ~sys_clk_n;")
tb_lines.append("")
tb_lines.append("    initial begin")
tb_lines.append("        sys_rst = 0; #1 sys_rst = 1; // proper negedge for dff init")
tb_lines.append("        #100 sys_rst = 0;")
tb_lines.append("    end")
tb_lines.append("")
tb_lines.append("    initial begin")
tb_lines.append('        $dumpfile("tb_top.vcd");')
tb_lines.append("        $dumpvars(0, tb_top);")
tb_lines.append("    end")
tb_lines.append("")
tb_lines.append("    initial begin")
tb_lines.append("        #100000;")
tb_lines.append("        forever begin")
tb_lines.append("            #10000;")
tb_lines.append('            $display("[%0t] locked=%b | Fout=%b | dtc_code=%0d | cal_done=%b",')
tb_lines.append("                     $time, u_dut.u_mmcm_pll.locked, u_dut.div_out_raw, u_dut.dtc_code, u_dut.cal_done);")
tb_lines.append("        end")
tb_lines.append("    end")
tb_lines.append("")
tb_lines.append("    initial begin")
tb_lines.append("        #2000000; // 2ms timeout")
tb_lines.append('        $display("TIMEOUT");')
tb_lines.append("        $finish;")
tb_lines.append("    end")
tb_lines.append("")
tb_lines.append("    initial begin")
tb_lines.append("        @(posedge u_dut.cal_done);")
tb_lines.append("        #50000;")
tb_lines.append('        $display("=== Calibration done ===");')
tb_lines.append('        $display("dtc_gain_cal=%0d", u_dut.dtc_gain_cal);')
tb_lines.append("        #100000;")
tb_lines.append("        $finish;")
tb_lines.append("    end")
tb_lines.append("endmodule")

with open("tb_top.v", "w", newline="\n") as f:
    for line in tb_lines:
        f.write(line + "\n")
print("Written tb_top.v")
