import os
os.chdir(r"D:\GS\项目\FPGA\xcvu9p-flga2104-2L-e\fpga_pll_mash111_dtc_ssc\RTL\testbench\openclaw")

lines = []
lines.append("`timescale 1ns / 1ps")
lines.append("module tb_top;")
lines.append("    parameter SYS_CLK_PERIOD = 8.0;")
lines.append("    reg sys_clk_p = 0; reg sys_clk_n = 0; reg sys_rst;")
lines.append("    wire sma_ref_p, sma_ref_n, sma_dtc_p, sma_dtc_n;")
lines.append("")
lines.append("    fpga_ssc_pll_top u_dut (")
lines.append("        .sys_clk_p(sys_clk_p), .sys_clk_n(sys_clk_n), .sys_rst(sys_rst),")
lines.append("        .sma_ref_p(sma_ref_p), .sma_ref_n(sma_ref_n),")
lines.append("        .sma_dtc_p(sma_dtc_p), .sma_dtc_n(sma_dtc_n));")
lines.append("")
lines.append("    always #(SYS_CLK_PERIOD/2) sys_clk_p = ~sys_clk_p;")
lines.append("    always #(SYS_CLK_PERIOD/2) sys_clk_n = ~sys_clk_n;")
lines.append("")
lines.append("    initial begin")
lines.append("        sys_rst = 0; #1 sys_rst = 1; #100 sys_rst = 0;")
lines.append("    end")
lines.append("")
lines.append("    initial begin")
lines.append('        $dumpfile("tb_top_jitter.vcd");')
lines.append("        $dumpvars(0, tb_top);")
lines.append("    end")
lines.append("")
lines.append("    // Jitter analysis")
lines.append("    reg [63:0] rmin=1000000000, rmax=0, rtot=0, rcnt=0, redge=0, rlast=0;")
lines.append("    reg [63:0] dmin=1000000000, dmax=0, dtot=0, dcnt=0, dedge=0, dlast=0;")
lines.append("")
lines.append("    always @(posedge u_dut.div_out_raw) begin")
lines.append("        if (rlast != 0 && redge > 100 && redge <= 200) begin")
lines.append("            rcnt <= rcnt + 1; rtot <= rtot + ($time - rlast);")
lines.append("            if ($time - rlast < rmin) rmin <= $time - rlast;")
lines.append("            if ($time - rlast > rmax) rmax <= $time - rlast;")
lines.append("        end")
lines.append("        rlast <= $time; redge <= redge + 1;")
lines.append("    end")
lines.append("")
lines.append("    always @(posedge sma_ref_p) begin")
lines.append("        if (dlast != 0 && dedge > 100 && dedge <= 200) begin")
lines.append("            dcnt <= dcnt + 1; dtot <= dtot + ($time - dlast);")
lines.append("            if ($time - dlast < dmin) dmin <= $time - dlast;")
lines.append("            if ($time - dlast > dmax) dmax <= $time - dlast;")
lines.append("        end")
lines.append("        dlast <= $time; dedge <= dedge + 1;")
lines.append("    end")
lines.append("")
lines.append("    initial begin")
lines.append("        #1800000;")
lines.append('        $display("");')
lines.append('        $display("=== Jitter Analysis (100 periods) ===");')
lines.append('        $display("--- Reference (div_out_raw) ---");')
lines.append("        if (rcnt > 0) begin")
lines.append('            $display("  Avg: %0d ps (%.1f ns)", rtot/rcnt, (rtot/rcnt)/1000.0);')
lines.append('            $display("  Min: %0d  Max: %0d  Jitter: %0d ps (%.1f%%)", rmin, rmax, rmax-rmin, (rmax-rmin)*100.0/(rtot/rcnt));')
lines.append("        end")
lines.append('        $display("--- DTC compensated (sma_ref_p) ---");')
lines.append("        if (dcnt > 0) begin")
lines.append('            $display("  Avg: %0d ps (%.1f ns)", dtot/dcnt, (dtot/dcnt)/1000.0);')
lines.append('            $display("  Min: %0d  Max: %0d  Jitter: %0d ps (%.1f%%)", dmin, dmax, dmax-dmin, (dmax-dmin)*100.0/(dtot/dcnt));')
lines.append("        end")
lines.append('        $display("Expected: 625MHz / 71.208 = 8.78MHz");')
lines.append("        $finish;")
lines.append("    end")
lines.append("endmodule")

with open("tb_top.v", "w", newline="\n") as f:
    f.write("\n".join(lines))
print("tb_top.v rewritten")
