# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/admin/Desktop/cygao/20260721/fpga_pll_mash111_dtc_ssc/fpga_pll_mash111_dtc_ssc/FPGA_SSC_PLL/FPGA_SSC_PLL.srcs/sources_1/ip/ila_dualdiv/ila_dualdiv.xci
# IP: The module: 'ila_dualdiv' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/admin/Desktop/cygao/20260721/fpga_pll_mash111_dtc_ssc/fpga_pll_mash111_dtc_ssc/FPGA_SSC_PLL/FPGA_SSC_PLL.gen/sources_1/ip/ila_dualdiv/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_dualdiv'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/admin/Desktop/cygao/20260721/fpga_pll_mash111_dtc_ssc/fpga_pll_mash111_dtc_ssc/FPGA_SSC_PLL/FPGA_SSC_PLL.gen/sources_1/ip/ila_dualdiv/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_dualdiv'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/admin/Desktop/cygao/20260721/fpga_pll_mash111_dtc_ssc/fpga_pll_mash111_dtc_ssc/FPGA_SSC_PLL/FPGA_SSC_PLL.gen/sources_1/ip/ila_dualdiv/ila_dualdiv_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_dualdiv'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/admin/Desktop/cygao/20260721/fpga_pll_mash111_dtc_ssc/fpga_pll_mash111_dtc_ssc/FPGA_SSC_PLL/FPGA_SSC_PLL.srcs/sources_1/ip/ila_dualdiv/ila_dualdiv.xci
# IP: The module: 'ila_dualdiv' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/admin/Desktop/cygao/20260721/fpga_pll_mash111_dtc_ssc/fpga_pll_mash111_dtc_ssc/FPGA_SSC_PLL/FPGA_SSC_PLL.gen/sources_1/ip/ila_dualdiv/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_dualdiv'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/admin/Desktop/cygao/20260721/fpga_pll_mash111_dtc_ssc/fpga_pll_mash111_dtc_ssc/FPGA_SSC_PLL/FPGA_SSC_PLL.gen/sources_1/ip/ila_dualdiv/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_dualdiv'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/admin/Desktop/cygao/20260721/fpga_pll_mash111_dtc_ssc/fpga_pll_mash111_dtc_ssc/FPGA_SSC_PLL/FPGA_SSC_PLL.gen/sources_1/ip/ila_dualdiv/ila_dualdiv_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_dualdiv'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
